import { Inter } from "next/font/google";

import MUIProvider from "@/themes/mui.provider";
import ReactQueryProvider from "@/services/queries/react-query/rq.provider";
import ReduxProvider from "@/store/provider";
import "../styles/index.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "initial-scale=1, width=device-width",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReactQueryProvider>
          <ReduxProvider>
            <MUIProvider>{children}</MUIProvider>
          </ReduxProvider>
        </ReactQueryProvider>
      </body>
    </html>
  );
}
